export interface Location {
  id: string;
  city: string;
  airport: string;
  code: string;
  coordinates: [number, number]; // [longitude, latitude]
}

export const airports: Location[] = [
  {
    id: "1",
    city: "Dubai",
    airport: "Dubai International Airport",
    code: "DXB",
    coordinates: [55.3644, 25.2532],
  },
  {
    id: "2",
    city: "New York",
    airport: "John F. Kennedy International Airport",
    code: "JFK",
    coordinates: [-73.7781, 40.6413],
  },
  {
    id: "3",
    city: "London",
    airport: "Heathrow Airport",
    code: "LHR",
    coordinates: [-0.4543, 51.47],
  },
  {
    id: "4",
    city: "Tokyo",
    airport: "Haneda Airport",
    code: "HND",
    coordinates: [139.7798, 35.5494],
  },
  {
    id: "5",
    city: "Paris",
    airport: "Charles de Gaulle Airport",
    code: "CDG",
    coordinates: [2.5479, 49.0097],
  },
  {
    id: "6",
    city: "Singapore",
    airport: "Changi Airport",
    code: "SIN",
    coordinates: [103.9915, 1.3644],
  },
  {
    id: "7",
    city: "Sydney",
    airport: "Sydney Airport",
    code: "SYD",
    coordinates: [151.1772, -33.9399],
  },
  {
    id: "8",
    city: "Istanbul",
    airport: "Istanbul Airport",
    code: "IST",
    coordinates: [28.7404, 41.2753],
  },
  {
    id: "9",
    city: "Berlin",
    airport: "Berlin Brandenburg Airport",
    code: "BER",
    coordinates: [13.5011, 52.3667],
  },
  {
    id: "10",
    city: "Rome",
    airport: "Leonardo da Vinci-Fiumicino Airport",
    code: "FCO",
    coordinates: [12.2389, 41.8003],
  },
  {
    id: "11",
    city: "Atlanta",
    airport: "Hartsfield-Jackson Atlanta",
    code: "ATL",
    coordinates: [-84.4277, 33.6407],
  },
  {
    id: "12",
    city: "Los Angeles",
    airport: "Los Angeles International",
    code: "LAX",
    coordinates: [-118.4085, 33.9416],
  },
  {
    id: "13",
    city: "Chicago",
    airport: "O'Hare International",
    code: "ORD",
    coordinates: [-87.9048, 41.9742],
  },
  {
    id: "14",
    city: "Dallas",
    airport: "Dallas/Fort Worth International",
    code: "DFW",
    coordinates: [-97.0403, 32.8998],
  },
  {
    id: "15",
    city: "Denver",
    airport: "Denver International",
    code: "DEN",
    coordinates: [-104.6737, 39.8561],
  },
  {
    id: "16",
    city: "San Francisco",
    airport: "San Francisco International",
    code: "SFO",
    coordinates: [-122.379, 37.6213],
  },
  {
    id: "17",
    city: "Frankfurt",
    airport: "Frankfurt Airport",
    code: "FRA",
    coordinates: [8.5706, 50.0333],
  },
  {
    id: "18",
    city: "Amsterdam",
    airport: "Amsterdam Airport Schiphol",
    code: "AMS",
    coordinates: [4.7683, 52.3105],
  },
  {
    id: "19",
    city: "Madrid",
    airport: "Adolfo Suárez Madrid-Barajas",
    code: "MAD",
    coordinates: [-3.5673, 40.4983],
  },
  {
    id: "20",
    city: "Barcelona",
    airport: "Josep Tarradellas Barcelona-El Prat",
    code: "BCN",
    coordinates: [2.0785, 41.2974],
  },
  {
    id: "21",
    city: "Beijing",
    airport: "Beijing Capital International",
    code: "PEK",
    coordinates: [116.5845, 40.0799],
  },
  {
    id: "22",
    city: "Hong Kong",
    airport: "Hong Kong International",
    code: "HKG",
    coordinates: [113.9145, 22.308],
  },
  {
    id: "23",
    city: "Seoul",
    airport: "Incheon International",
    code: "ICN",
    coordinates: [126.4407, 37.4602],
  },
  {
    id: "24",
    city: "New Delhi",
    airport: "Indira Gandhi International",
    code: "DEL",
    coordinates: [77.1, 28.5562],
  },
  {
    id: "25",
    city: "Mumbai",
    airport: "Chhatrapati Shivaji Maharaj",
    code: "BOM",
    coordinates: [72.8656, 19.0896],
  },
  {
    id: "26",
    city: "São Paulo",
    airport: "São Paulo/Guarulhos International",
    code: "GRU",
    coordinates: [-46.4731, -23.4356],
  },
  {
    id: "27",
    city: "Bogotá",
    airport: "El Dorado International",
    code: "BOG",
    coordinates: [-74.1469, 4.7016],
  },
  {
    id: "28",
    city: "Lima",
    airport: "Jorge Chávez International",
    code: "LIM",
    coordinates: [-77.1143, -12.0219],
  },
  {
    id: "29",
    city: "Santiago",
    airport: "Arturo Merino Benítez",
    code: "SCL",
    coordinates: [-70.7858, -33.393],
  },
  {
    id: "30",
    city: "Buenos Aires",
    airport: "Ministro Pistarini International",
    code: "EZE",
    coordinates: [-58.5358, -34.8222],
  },
  {
    id: "31",
    city: "Johannesburg",
    airport: "O. R. Tambo International",
    code: "JNB",
    coordinates: [28.246, -26.1392],
  },
  {
    id: "32",
    city: "Cairo",
    airport: "Cairo International",
    code: "CAI",
    coordinates: [31.4056, 30.1219],
  },
  {
    id: "33",
    city: "Casablanca",
    airport: "Mohammed V International",
    code: "CMN",
    coordinates: [-7.5898, 33.3675],
  },
  {
    id: "34",
    city: "Tangier",
    airport: "Tangier Ibn Battouta Airport",
    code: "TNG",
    coordinates: [-5.9168, 35.7269],
  },
  {
    id: "35",
    city: "Bangkok",
    airport: "Suvarnabhumi Airport",
    code: "BKK",
    coordinates: [100.7501, 13.69],
  },
  {
    id: "36",
    city: "Kuala Lumpur",
    airport: "Kuala Lumpur International",
    code: "KUL",
    coordinates: [101.7099, 2.7456],
  },
  {
    id: "37",
    city: "Jakarta",
    airport: "Soekarno-Hatta International",
    code: "CGK",
    coordinates: [106.6558, -6.1256],
  },
  {
    id: "38",
    city: "Doha",
    airport: "Hamad International Airport",
    code: "DOH",
    coordinates: [51.608, 25.273],
  },
  {
    id: "39",
    city: "Abu Dhabi",
    airport: "Zayed International Airport",
    code: "AUH",
    coordinates: [54.6511, 24.433],
  },
  {
    id: "40",
    city: "Toronto",
    airport: "Toronto Pearson International",
    code: "YYZ",
    coordinates: [-79.6248, 43.6777],
  },
  {
    id: "41",
    city: "Vancouver",
    airport: "Vancouver International",
    code: "YVR",
    coordinates: [-123.184, 49.1967],
  },
  {
    id: "42",
    city: "Munich",
    airport: "Munich Airport",
    code: "MUC",
    coordinates: [11.7861, 48.3537],
  },
  {
    id: "43",
    city: "Dublin",
    airport: "Dublin Airport",
    code: "DUB",
    coordinates: [-6.2499, 53.4264],
  },
  {
    id: "44",
    city: "Zurich",
    airport: "Zurich Airport",
    code: "ZRH",
    coordinates: [8.5492, 47.4582],
  },
  {
    id: "45",
    city: "Copenhagen",
    airport: "Copenhagen Airport",
    code: "CPH",
    coordinates: [12.656, 55.618],
  },
  {
    id: "46",
    city: "Stockholm",
    airport: "Stockholm Arlanda Airport",
    code: "ARN",
    coordinates: [17.9186, 59.6519],
  },
  {
    id: "47",
    city: "Las Vegas",
    airport: "Harry Reid International",
    code: "LAS",
    coordinates: [-115.1523, 36.084],
  },
  {
    id: "48",
    city: "Orlando",
    airport: "Orlando International",
    code: "MCO",
    coordinates: [-81.309, 28.4312],
  },
  {
    id: "49",
    city: "Seattle",
    airport: "Seattle-Tacoma International",
    code: "SEA",
    coordinates: [-122.3088, 47.4502],
  },
  {
    id: "50",
    city: "Vienna",
    airport: "Vienna International",
    code: "VIE",
    coordinates: [16.5697, 48.1103],
  },
  {
    id: "51",
    city: "Taipei",
    airport: "Taoyuan International Airport",
    code: "TPE",
    coordinates: [121.2328, 25.0777],
  },
  {
    id: "52",
    city: "Manila",
    airport: "Ninoy Aquino International",
    code: "MNL",
    coordinates: [121.0194, 14.5086],
  },
  {
    id: "53",
    city: "Ho Chi Minh City",
    airport: "Tan Son Nhat International",
    code: "SGN",
    coordinates: [106.6625, 10.8116],
  },
  {
    id: "54",
    city: "Melbourne",
    airport: "Melbourne Airport",
    code: "MEL",
    coordinates: [144.8433, -37.669],
  },
  {
    id: "55",
    city: "Brisbane",
    airport: "Brisbane Airport",
    code: "BNE",
    coordinates: [153.1175, -27.3842],
  },
  {
    id: "56",
    city: "Auckland",
    airport: "Auckland Airport",
    code: "AKL",
    coordinates: [174.7986, -37.0082],
  },
  {
    id: "57",
    city: "Honolulu",
    airport: "Daniel K. Inouye International",
    code: "HNL",
    coordinates: [-157.9225, 21.3187],
  },
  {
    id: "58",
    city: "Miami",
    airport: "Miami International Airport",
    code: "MIA",
    coordinates: [-80.287, 25.7959],
  },
  {
    id: "59",
    city: "Boston",
    airport: "Logan International Airport",
    code: "BOS",
    coordinates: [-71.0023, 42.3656],
  },
  {
    id: "60",
    city: "Washington D.C.",
    airport: "Dulles International Airport",
    code: "IAD",
    coordinates: [-77.4565, 38.9531],
  },
  {
    id: "61",
    city: "Philadelphia",
    airport: "Philadelphia International",
    code: "PHL",
    coordinates: [-75.2411, 39.8729],
  },
  {
    id: "62",
    city: "Charlotte",
    airport: "Charlotte Douglas International",
    code: "CLT",
    coordinates: [-80.9431, 35.214],
  },
  {
    id: "63",
    city: "Houston",
    airport: "George Bush Intercontinental",
    code: "IAH",
    coordinates: [-95.3368, 29.9902],
  },
  {
    id: "64",
    city: "Phoenix",
    airport: "Phoenix Sky Harbor International",
    code: "PHX",
    coordinates: [-112.0078, 33.4342],
  },
  {
    id: "65",
    city: "Detroit",
    airport: "Detroit Metropolitan Wayne County",
    code: "DTW",
    coordinates: [-83.3488, 42.2121],
  },
  {
    id: "66",
    city: "Minneapolis",
    airport: "Minneapolis-Saint Paul International",
    code: "MSP",
    coordinates: [-93.2218, 44.8848],
  },
  {
    id: "67",
    city: "Montreal",
    airport: "Montréal-Pierre Elliott Trudeau",
    code: "YUL",
    coordinates: [-73.7408, 45.4706],
  },
  {
    id: "68",
    city: "Calgary",
    airport: "Calgary International Airport",
    code: "YYC",
    coordinates: [-114.0076, 51.1215],
  },
  {
    id: "69",
    city: "Mexico City",
    airport: "Benito Juárez International",
    code: "MEX",
    coordinates: [-99.0721, 19.4361],
  },
  {
    id: "70",
    city: "Cancún",
    airport: "Cancún International Airport",
    code: "CUN",
    coordinates: [-86.8744, 21.0367],
  },
  {
    id: "71",
    city: "Panama City",
    airport: "Tocumen International Airport",
    code: "PTY",
    coordinates: [-79.3834, 9.0715],
  },
  {
    id: "72",
    city: "Rio de Janeiro",
    airport: "Galeão International Airport",
    code: "GIG",
    coordinates: [-43.2436, -22.8089],
  },
  {
    id: "73",
    city: "Helsinki",
    airport: "Helsinki-Vantaa Airport",
    code: "HEL",
    coordinates: [24.9633, 60.3172],
  },
  {
    id: "74",
    city: "Oslo",
    airport: "Oslo Gardermoen Airport",
    code: "OSL",
    coordinates: [11.1004, 60.1939],
  },
  {
    id: "75",
    city: "Geneva",
    airport: "Geneva Airport",
    code: "GVA",
    coordinates: [6.1092, 46.237],
  },
  {
    id: "76",
    city: "Brussels",
    airport: "Brussels Airport",
    code: "BRU",
    coordinates: [4.4844, 50.9014],
  },
  {
    id: "77",
    city: "Lisbon",
    airport: "Humberto Delgado Airport",
    code: "LIS",
    coordinates: [-9.1359, 38.7742],
  },
  {
    id: "78",
    city: "Milan",
    airport: "Milan Malpensa Airport",
    code: "MXP",
    coordinates: [8.7281, 45.6301],
  },
  {
    id: "79",
    city: "Athens",
    airport: "Athens International Airport",
    code: "ATH",
    coordinates: [23.9445, 37.9364],
  },
  {
    id: "80",
    city: "Warsaw",
    airport: "Warsaw Chopin Airport",
    code: "WAW",
    coordinates: [20.9671, 52.1657],
  },
  {
    id: "81",
    city: "Prague",
    airport: "Václav Havel Airport Prague",
    code: "PRG",
    coordinates: [14.26, 50.1008],
  },
  {
    id: "82",
    city: "Budapest",
    airport: "Budapest Ferenc Liszt International",
    code: "BUD",
    coordinates: [19.2611, 47.4369],
  },
  {
    id: "83",
    city: "Manchester",
    airport: "Manchester Airport",
    code: "MAN",
    coordinates: [-2.275, 53.3537],
  },
  {
    id: "84",
    city: "Edinburgh",
    airport: "Edinburgh Airport",
    code: "EDI",
    coordinates: [-3.3615, 55.95],
  },
  {
    id: "85",
    city: "Riyadh",
    airport: "King Khalid International Airport",
    code: "RUH",
    coordinates: [46.6988, 24.9576],
  },
  {
    id: "86",
    city: "Jeddah",
    airport: "King Abdulaziz International Airport",
    code: "JED",
    coordinates: [39.1565, 21.6796],
  },
  {
    id: "87",
    city: "Muscat",
    airport: "Muscat International Airport",
    code: "MCT",
    coordinates: [58.2817, 23.5933],
  },
  {
    id: "88",
    city: "Manama",
    airport: "Bahrain International Airport",
    code: "BAH",
    coordinates: [50.6336, 26.2708],
  },
  {
    id: "89",
    city: "Kuwait City",
    airport: "Kuwait International Airport",
    code: "KWI",
    coordinates: [47.9689, 25.2399],
  },
  {
    id: "90",
    city: "Tel Aviv",
    airport: "Ben Gurion Airport",
    code: "TLV",
    coordinates: [34.8867, 32.0114],
  },
  {
    id: "91",
    city: "Nairobi",
    airport: "Jomo Kenyatta International",
    code: "NBO",
    coordinates: [36.9275, -1.3192],
  },
  {
    id: "92",
    city: "Addis Ababa",
    airport: "Bole International Airport",
    code: "ADD",
    coordinates: [38.7993, 8.9778],
  },
  {
    id: "93",
    city: "Cape Town",
    airport: "Cape Town International Airport",
    code: "CPT",
    coordinates: [18.6017, -33.9715],
  },
  {
    id: "94",
    city: "Lagos",
    airport: "Murtala Muhammed International",
    code: "LOS",
    coordinates: [3.3211, 6.5774],
  },
  {
    id: "95",
    city: "Accra",
    airport: "Kotoka International Airport",
    code: "ACC",
    coordinates: [-0.1666, 5.6052],
  },
  {
    id: "96",
    city: "Dakar",
    airport: "Blaise Diagne International",
    code: "DSS",
    coordinates: [-17.0733, 14.67],
  },
  {
    id: "97",
    city: "Marrakech",
    airport: "Marrakech Menara Airport",
    code: "RAK",
    coordinates: [-8.0363, 31.6069],
  },
  {
    id: "98",
    city: "Algiers",
    airport: "Houari Boumediene Airport",
    code: "ALG",
    coordinates: [3.2163, 36.691],
  },
  {
    id: "99",
    city: "Tunis",
    airport: "Tunis-Carthage International",
    code: "TUN",
    coordinates: [10.2272, 36.851],
  },
  {
    id: "100",
    city: "Osaka",
    airport: "Kansai International Airport",
    code: "KIX",
    coordinates: [135.244, 34.4347],
  },
  {
    id: "101",
    city: "Norfolk",
    airport: "Norfolk International Airport",
    code: "ORF",
    coordinates: [-76.2012, 36.8946],
  },
  {
    id: "102",
    city: "Newport News",
    airport: "Newport News/Williamsburg Airport",
    code: "PHF",
    coordinates: [-76.493, 37.1319],
  },
  {
    id: "103",
    city: "Richmond",
    airport: "Richmond International Airport",
    code: "RIC",
    coordinates: [-77.3197, 37.5052],
  },
  {
    id: "104",
    city: "Washington D.C.",
    airport: "Ronald Reagan Washington National",
    code: "DCA",
    coordinates: [-77.0377, 38.8512],
  },
  {
    id: "105",
    city: "Baltimore",
    airport: "Baltimore/Washington International",
    code: "BWI",
    coordinates: [-76.6683, 39.1754],
  },
  {
    id: "ga-teb",
    city: "Teterboro / New York",
    airport: "Teterboro Airport (Executive FBO)",
    code: "TEB",
    coordinates: [-74.061, 40.8501],
  },
  {
    id: "ga-pdk",
    city: "Atlanta",
    airport: "DeKalb-Peachtree Airport (Signature PDK)",
    code: "PDK",
    coordinates: [-84.302, 33.8756],
  },
  {
    id: "ga-lzu",
    city: "Atlanta / Lawrenceville",
    airport: "Gwinnett County Airport - Briscoe Field",
    code: "LZU",
    coordinates: [-83.9622, 33.9786],
  },
  {
    id: "ga-ryy",
    city: "Atlanta / Kennesaw",
    airport: "Cobb County International - McCollum Field",
    code: "RYY",
    coordinates: [-84.5975, 34.0131],
  },
  {
    id: "ga-fty",
    city: "Atlanta",
    airport: "Fulton County Airport - Charlie Brown Field",
    code: "FTY",
    coordinates: [-84.5214, 33.7791],
  },
  {
    id: "ga-vny",
    city: "Los Angeles / Van Nuys",
    airport: "Van Nuys Airport (Signature/Clay Lacy)",
    code: "VNY",
    coordinates: [-118.4900, 34.2098],
  },
  {
    id: "ga-hpn",
    city: "White Plains / New York",
    airport: "Westchester County Airport",
    code: "HPN",
    coordinates: [-73.7076, 41.0669],
  },
  {
    id: "ga-opf",
    city: "Miami / Opa-locka",
    airport: "Miami-Opa Locka Executive Airport (Fontainebleau)",
    code: "OPF",
    coordinates: [-80.2784, 25.9070],
  },
  {
    id: "ga-fxe",
    city: "Fort Lauderdale",
    airport: "Fort Lauderdale Executive Airport",
    code: "FXE",
    coordinates: [-80.1707, 26.1973],
  },
  {
    id: "ga-bct",
    city: "Boca Raton",
    airport: "Boca Raton Airport (Signature / Atlantic)",
    code: "BCT",
    coordinates: [-80.1077, 26.3785],
  },
  {
    id: "ga-ase",
    city: "Aspen",
    airport: "Aspen/Pitkin County Airport (Sardy Field)",
    code: "ASE",
    coordinates: [-106.8688, 39.2232],
  },
  {
    id: "ga-ege",
    city: "Vail / Eagle",
    airport: "Eagle County Regional Airport",
    code: "EGE",
    coordinates: [-106.9177, 39.6426],
  },
  {
    id: "ga-apa",
    city: "Denver / Englewood",
    airport: "Centennial Airport (Signature / Modern)",
    code: "APA",
    coordinates: [-104.8493, 39.5701],
  },
  {
    id: "ga-dal",
    city: "Dallas",
    airport: "Dallas Love Field (Business Aviation)",
    code: "DAL",
    coordinates: [-96.8518, 32.8471],
  },
  {
    id: "ga-sdl",
    city: "Scottsdale / Phoenix",
    airport: "Scottsdale Airport (Signature / Jet Aviation)",
    code: "SDL",
    coordinates: [-111.9105, 33.6229],
  },
  {
    id: "ga-apf",
    city: "Naples",
    airport: "Naples Municipal Airport",
    code: "APF",
    coordinates: [-81.7753, 26.1526],
  },
];
